### ISSUE TITLE
Switching characters in vista/radio screen can cause graphical glitches

### ISSUE THREAD

**Issue by tag2015** [scemino/scummvm#11]
Changing character (and going back to the original character) while on the vista, radio or the bridge screens can cause graphical glitches, with duplicated fireflies/birds all over the screen.

Win 10 / HEAD 62009e057062ea49083ed625bec9fb655d0c88e9

**Comment by scemino** [comment]
Fixed by 8a699935c8620f9ea516320714f2af1fa8df79d5
