### ISSUE TITLE
Walkspeed is much slower compared to original

### ISSUE THREAD

**Issue by tag2015** [scemino/scummvm#12]
This is probably a known issue, but the walkspeed is much slower compared to the original. This is especially annoying in the map screen since moving from the bridge to the Edmund mansion can take more than 20 seconds.

Win 10 / HEAD 62009e057062ea49083ed625bec9fb655d0c88e9

**Comment by scemino** [comment]
Fixed by 2323e97248f9b5b3cadc6e05bba0e15eef4ee178
