### ISSUE TITLE
Missing animations in some locations

### ISSUE THREAD

**Issue by tag2015** [scemino/scummvm#13]
Some animations are missing:
- When Chet advertises the Pizza Meeting, he doesn't speak/move his hands
- During the first meeting Delores/Lenore in the library, Lenore doesn't speak while he walks
- The bank teller doesn't speak when he answers the phone

(there may be others)

**Comment by scemino** [comment]
I know how to fix this but it creates a regression with Willie losing his head when snoring.

**Comment by scemino** [comment]
Fixed by 922ba51bf816ea983da9d80d3dc31a6a842aaf65
