### ISSUE TITLE
Dialogue behavior is incorrect in (at least) two occasions

### ISSUE THREAD

**Issue by tag2015** [scemino/scummvm#16]
During the agents comeback cutscene, when Ray is talking and you pick the "japanese company" line, she should look at you and then say the "mission for the NSA" line, instead.
In scummvm, she says both lines sequentially.

A similar issue happens when, using Franklin, you speak with Xavier. If you pick the "you're a bully and a tyrant" line early on, franklin should just say "sorry to bother you".

Save in bugreport #5

**Comment by scemino** [comment]
Good point, I never noticed it!

**Comment by tag2015** [comment]
moved to https://bugs.scummvm.org/
