### ISSUE TITLE
During the ComiCon radio trivia some questions are not played

### ISSUE THREAD

**Issue by tag2015** [scemino/scummvm#17]
Haven't checked with the game (so it could be an original bug) but in scummvm the trivia/quiz questions speech is not played.

See attached save 
- Switch to delores, remove tube, reinstall tube
- Switch to ransome, call 7286

[quiz.zip](https://github.com/scemino/scummvm/files/14619828/quiz.zip)

**Comment by scemino** [comment]
Fix with commit ea799ec95afd871e50c7024276a77ef6b6c3edf9
