### ISSUE TITLE
Verbs/inventory area allows clicking on background

### ISSUE THREAD

**Issue by tag2015** [scemino/scummvm#18]
Currently, clicks are only registered if the pointer is precisely on a verb, not in its "bounding box".
This (often) allows clicking on the background, causing the character to perform a "walk to" the clicked location.
A similar issue occurs in the inventory, where you can click in the area between the icons and also (sometimes) trigger a walkto clicking the same icon more than once.

**Comment by scemino** [comment]
Fixed in 6924e2e92492492d1a2ef144d96b079565428ec2
