### ISSUE TITLE
Pizza flyer missing codes [hard mode]

### ISSUE THREAD

**Issue by tag2015** [scemino/scummvm#2]
The pizza flyer that Chet drops should have a code printed at the bottom.
When playing using ScummVM, the area is blank. Since the code is later used in a puzzle, hard mode is not completable.

Win10 / latest HEAD (3c4d7628bc10a7e9f27b64c7b26e9218b70c5ad6)

[save.zip](https://github.com/scemino/scummvm/files/14540178/save.zip)

**Comment by scemino** [comment]
Oh I see that's a problem, actually it's almost visible, it's just not at the right position:
<img width="1392" alt="pizza_coupon" src="https://github.com/scemino/scummvm/assets/643384/7f63d61e-fed9-43f7-b054-3f8172e3aa3e">

I need to fix that, thanks.

**Comment by scemino** [comment]
Fixed by e03e7d307ba0bf58c793b6dadce651fcc997ce18
