### ISSUE TITLE
Verbs/inventory area can interfere with lower area of map screen

### ISSUE THREAD

**Issue by tag2015** [scemino/scummvm#20]
The gui should be completely disabled when using the map screen. Currently, clicking in the lower area can trigger one of the verbs.
This is easily noticeable clicking the vista/hotel hotspots. Often the character says "i can't push that" or "looks fine to me" instead of moving to the location.

**Comment by scemino** [comment]
Fixed in 6924e2e92492492d1a2ef144d96b079565428ec2
