### ISSUE TITLE
Skipping cutscenes with ESC can leave the game in an unusable state

### ISSUE THREAD

**Issue by tag2015** [scemino/scummvm#3]
The game lets you skip some cutscenes pressing ESC, but often this doesn't work properly.
See attached save. Use the reports with the ArrestTron and then skip the sheriff cutscene.
If you press ESC multiple times, Ray will repeat the "good cop/bad cop" message. If you continue, the screen won't scroll and when you complete the dialogue and control moves to Delores, you won't be able to do anything.
This is an example but it also happens in other situations.
[save.zip](https://github.com/scemino/scummvm/files/14540527/save.zip)

**Comment by scemino** [comment]
Now it's not possible to call sevaral times a cutscene override with this commit 62009e057062ea49083ed625bec9fb655d0c88e9 BUT the game is still in invalid state.

**Comment by tag2015** [comment]
moved to https://bugs.scummvm.org/
