### ISSUE TITLE
"Meanwhile..." agents cutscene doesn't trigger

### ISSUE THREAD

**Issue by tag2015** [scemino/scummvm#5]
See attached save
When leaving the convention, the agents comeback cutscene should trigger (that's what happens loading the save on the original interpreter).
Using ScummVM, this doesn't happen and there's no way to proceed (I also tried leaving the hotel, changing characters, etc.)

[convention.zip](https://github.com/scemino/scummvm/files/14542197/convention.zip)

**Comment by scemino** [comment]
Fixed by 1d5430dc587fb7970aba275b5ab6540b6f9c35be
