### ISSUE TITLE
Using phone/elevator buttons with Franklin can trigger an assert

### ISSUE THREAD

**Issue by tag2015** [scemino/scummvm#6]
Doesn't happen always, but often clicking the area of the 0/OPER button, using Franklin can cause an assert:
Assertion failed: amin <= amax, file ./common/util.h, line 72

See attached save
1. Change to Franklin
2. Enter any room
3. Zap phone

A similar issue happens clicking around the Lobby/Mezzanine buttons
Win 10 / HEAD 62009e057062ea49083ed625bec9fb655d0c88e9
[twp_fan.zip](https://github.com/scemino/scummvm/files/14550916/twp_fan.zip)

**Comment by scemino** [comment]
Yes, this `CLIP` method is quite annoying, I had a different implementation which was less restrictive.

**Comment by scemino** [comment]
FIx with e7f130c5321736eb1feb74a24e1304dcc86017fe
