### ISSUE TITLE
Deactivated fan still spinning

### ISSUE THREAD

**Issue by tag2015** [scemino/scummvm#7]
When you call the service line the huge fan gets properly disabled (you can walk through it) but the spin animation stays active.

Can be reproduced using the same save of bugreport #6
1. Read sign
2. Switch to Franklin and call number

Win 10 / HEAD 62009e057062ea49083ed625bec9fb655d0c88e9

**Comment by scemino** [comment]
Fixed with 0a4e0e6d56fab9bf7de98bc1c2d75b5325e0fd5a
