### ISSUE TITLE
"Revelation" dialogue is quite broken

### ISSUE THREAD

**Issue by tag2015** [scemino/scummvm#8]
See attached save, just push one of the tubes
The following issues are noticeable:
- Delores reads the lines that are said by the computer
- There's no speech for the computer lines
- After the big revelation, Delores doesn't animate anymore when saying her lines

The "stuck" animation fixes itself when the other characters enter the room
[twp_ptron.zip](https://github.com/scemino/scummvm/files/14550966/twp_ptron.zip)

**Comment by scemino** [comment]
The commit e9b3919db125bd6b61534c7c9370221076ad4c70 fixes point 1 and point 2.
I still don't know how to fix number 3.

**Comment by scemino** [comment]
Number 3 is fixed by 7c4f21d7a85f22f8c418c966484c5f56fa78949d
