### ISSUE TITLE
Takeover song playing multiple times can prevent Willie puzzle from being solved

### ISSUE THREAD

**Issue by tag2015** [scemino/scummvm#9]
See attached save
Enter radio station using ray, then alternate between her and Ransome a couple times. An addional "takeover" song starts playing each time.
This can prevent the Willie puzzle from being solved because even if you disable the antenna and put the correct record on he'll refuse to work.
Win 10 / HEAD 62009e057062ea49083ed625bec9fb655d0c88e9

A similar issue occurs when Delores dances, the dance song keeps playing in the backround (same thing when you give the trophy using Ray at the end of the game)

[twp_radio.zip](https://github.com/scemino/scummvm/files/14551003/twp_radio.zip)

**Comment by scemino** [comment]
Fixed by commit c96007ae620b6dbd09131cdb9ef350e088b7e273
